github-mirror: https://mirror.ghproxy.com/
data:
  - id: _pool
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/airport/main/subs/_pool.yaml
    output: subs/_pool.yaml
  - id: aiboboxx
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
    output: subs/aiboboxx.yaml
  - id: anaer
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
    output: subs/anaer.yaml
  - id: changfengoss
    type: github
    source: clash
    target: clash
    urls:
      - https://github.com/changfengoss/pub
    output: subs/changfengoss.yaml
    options:
      span: 1209600000
      exts: .yaml
  - id: chengaopan
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
    output: subs/chengaopan.yaml
  - id: fromzero
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/proxy_workers/main/subs/fromzero.yaml
    output: subs/fromzero.yaml
  - id: hkaa0
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
    output: subs/hkaa0.yaml
  - id: mahdibland
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml
      - https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir.yml
    output: subs/mahdibland.yaml
  - id: peasoft
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.yml
    output: subs/peasoft.yaml
  - id: ripaojiedian
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
    output: subs/ripaojiedian.yaml
  - id: soroushmirzaei
    type: http
    source: v2ray
    target: clash
    urls:
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/ws
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/grpc
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/http
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/tcp
      - https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/ws
    output: subs/soroushmirzaei.yaml
  - id: tssf
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/ts-sf/fly/main/clash
    output: subs/tssf.yaml
  - id: ttvg
    type: http
    source: clash
    target: clash
    urls:
      - https://tt.vg/freeclash
    output: subs/ttvg.yaml
  - id: xrayvip
    type: http
    source: clash
    target: clash
    urls:
      - https://www.xrayvip.com/free.yaml
    output: subs/xrayvip.yaml
  - id: yudou
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/dongchengjie/proxy_workers/main/subs/yudou.yaml
    output: subs/yudou.yaml
  - id: zhangkaiitugithub
    type: http
    source: clash
    target: clash
    urls:
      - https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
    output: subs/zhangkaiitugithub.yaml
